In [1]:
import polars as pl

In [53]:
df = pl.read_parquet("data_raw/segments/*.parquet")

df = df.with_columns(
    (pl.col("date").cast(pl.Int64) * 1000000).cast(pl.Datetime(time_zone='CET'))
)
df = df.filter(pl.col('date').dt.hour() > 22)
df = df.sort(by="date")

In [63]:
df.columns

['id',
 'resource_state',
 'name',
 'activity_type',
 'distance',
 'average_grade',
 'maximum_grade',
 'elevation_high',
 'elevation_low',
 'start_latlng',
 'end_latlng',
 'elevation_profile',
 'elevation_profiles',
 'climb_category',
 'city',
 'state',
 'country',
 'private',
 'hazardous',
 'starred',
 'created_at',
 'updated_at',
 'total_elevation_gain',
 'map',
 'effort_count',
 'athlete_count',
 'star_count',
 'athlete_segment_stats',
 'xoms',
 'local_legend',
 'date']

In [71]:
df.group_by_dynamic("date", by="name", every="1d").agg(pl.col("effort_count").max())

C:\Users\micha\AppData\Local\Temp\ipykernel_14396\3197359101.py:1: DeprecationWarning: The argument `by` for `DataFrame.group_by_dynamic` is deprecated. It has been renamed to `group_by`.
  df.group_by_dynamic("date", by="name", every="1d").agg(pl.col("effort_count").max())

shape: (3_190, 3)
┌─────────────────────────────────┬─────────────────────────┬──────────────┐
│ name                            ┆ date                    ┆ effort_count │
│ ---                             ┆ ---                     ┆ ---          │
│ str                             ┆ datetime[μs, CET]       ┆ i64          │
╞═════════════════════════════════╪═════════════════════════╪══════════════╡
│ Dlouhe Strane od Loucnej        ┆ 2024-12-24 00:00:00 CET ┆ 308          │
│ Dlouhe Strane od Loucnej        ┆ 2024-12-25 00:00:00 CET ┆ 308          │
│ Dlouhe Strane od Loucnej        ┆ 2024-12-26 00:00:00 CET ┆ 308          │
│ Dlouhe Strane od Loucnej        ┆ 2024-12-27 00:00:00 CET ┆ 308          │
│ Dlouhe Strane od Loucnej        ┆ 2024-12-28 00:00:00 CET ┆ 308          │
│ …                               ┆ …                       ┆ …            │
│ Sprintík křižovatka/skalní mlý… ┆ 2025-01-02 00:00:00 CET ┆ 30465        │
│ Sprintík křižovatka/skalní mlý… ┆ 2025-01-03 00:00:00 CET ┆ 30464        │
│ Sprintík křižovatka/skalní mlý… ┆ 2025-01-04 00:00:00 CET ┆ 30467        │
│ Sprintík křižovatka/skalní mlý… ┆ 2025-01-05 00:00:00 CET ┆ 30470        │
│ Sprintík křižovatka/skalní mlý… ┆ 2025-01-06 00:00:00 CET ┆ 30470        │
└─────────────────────────────────┴─────────────────────────┴──────────────┘

In [79]:
df

shape: (3_349, 31)
┌──────────┬──────────────┬──────────────┬──────────────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ id       ┆ resource_sta ┆ name         ┆ activity_typ ┆ … ┆ athlete_segm ┆ xoms        ┆ local_legen ┆ date        │
│ ---      ┆ te           ┆ ---          ┆ e            ┆   ┆ ent_stats    ┆ ---         ┆ d           ┆ ---         │
│ i64      ┆ ---          ┆ str          ┆ ---          ┆   ┆ ---          ┆ struct[4]   ┆ ---         ┆ datetime[μs │
│          ┆ i64          ┆              ┆ str          ┆   ┆ struct[6]    ┆             ┆ struct[7]   ┆ , CET]      │
╞══════════╪══════════════╪══════════════╪══════════════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 17521739 ┆ 3            ┆ Dlouhe       ┆ Ride         ┆ … ┆ {null,null,n ┆ {"43:55","1 ┆ {13919744," ┆ 2024-12-24  │
│          ┆              ┆ Strane od    ┆              ┆   ┆ ull,null,nul ┆ :00:24","43 ┆ Kamil Filip ┆ 23:02:03    │
│          ┆              ┆ Loucnej      ┆              ┆   ┆ l,0}         ┆ :55",{"s…   ┆ ek","htt…   ┆ CET         │
│ 8598488  ┆ 3            ┆ Lysa hora -  ┆ Run          ┆ … ┆ {null,null,n ┆ {"1:47","2: ┆ {109095258, ┆ 2024-12-24  │
│          ┆              ┆ jizni        ┆              ┆   ┆ ull,null,nul ┆ 00","1:47", ┆ "Roman Gula ┆ 23:02:11    │
│          ┆              ┆ sjezdovka    ┆              ┆   ┆ l,0}         ┆ {"strava…   ┆ ","https…   ┆ CET         │
│ 10356069 ┆ 3            ┆ Kvilda       ┆ Ride         ┆ … ┆ {null,null,n ┆ {"10:47","1 ┆ {3478016,"T ┆ 2024-12-24  │
│          ┆              ┆ Bučina       ┆              ┆   ┆ ull,null,nul ┆ 3:11","10:4 ┆ yrel Fuchs" ┆ 23:02:12    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ 7",{"str…   ┆ ,"https:…   ┆ CET         │
│ 13477973 ┆ 3            ┆ Od dubu ke   ┆ Run          ┆ … ┆ {130,"2022-0 ┆ {"1:04","1: ┆ {31102876," ┆ 2024-12-24  │
│          ┆              ┆ Gizele       ┆              ┆   ┆ 9-28","every ┆ 16","1:04", ┆ Evžen Demče ┆ 23:02:12    │
│          ┆              ┆              ┆              ┆   ┆ one",7…      ┆ {"strava…   ┆ nko","ht…   ┆ CET         │
│ 7116683  ┆ 3            ┆ Risova       ┆ Ride         ┆ … ┆ {603,"2024-0 ┆ {"5:46","7: ┆ {6149474,"R ┆ 2024-12-24  │
│          ┆              ┆ studanka -   ┆              ┆   ┆ 9-08","every ┆ 18","5:46", ┆ obert Šmíd" ┆ 23:05:01    │
│          ┆              ┆ od zavory    ┆              ┆   ┆ one",1…      ┆ {"strava…   ┆ ,"https:…   ┆ CET         │
│ …        ┆ …            ┆ …            ┆ …            ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ 34202323 ┆ 3            ┆ Podél        ┆ Ride         ┆ … ┆ {null,null,n ┆ {"15:37","1 ┆ {8766631,"T ┆ 2025-01-06  │
│          ┆              ┆ dálnice      ┆              ┆   ┆ ull,null,nul ┆ 8:32","15:3 ┆ ekato Soulb ┆ 23:38:33    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ 7",{"str…   ┆ ass","ht…   ┆ CET         │
│ 6879538  ┆ 3            ┆ Údolí Svatý  ┆ Ride         ┆ … ┆ {null,null,n ┆ {"8:16","10 ┆ {44938324," ┆ 2025-01-06  │
│          ┆              ┆ Jan          ┆              ┆   ┆ ull,null,nul ┆ :36","8:16" ┆ Jakub Rečka ┆ 23:38:33    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ ,{"strav…   ┆ ","https…   ┆ CET         │
│ 15082676 ┆ 3            ┆ Tyršák       ┆ Run          ┆ … ┆ {null,null,n ┆ {"59s","1:0 ┆ {76800198," ┆ 2025-01-06  │
│          ┆              ┆ čtyřstofka   ┆              ┆   ┆ ull,null,nul ┆ 8","59s",{" ┆ Jan Miča"," ┆ 23:38:34    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ strava:/…   ┆ https://…   ┆ CET         │
│ 16197668 ┆ 3            ┆ Stezka       ┆ Run          ┆ … ┆ {null,null,n ┆ {"1:34","1: ┆ {7145582,"P ┆ 2025-01-06  │
│          ┆              ┆ nábřeží      ┆              ┆   ┆ ull,null,nul ┆ 42","1:34", ┆ avel Gajdos ┆ 23:38:34    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ {"strava…   ┆ ik","htt…   ┆ CET         │
│ 37578163 ┆ 3            ┆ Lacinův      ┆ Hike         ┆ … ┆ {null,null,n ┆ {"19:45","2 ┆ {37351697," ┆ 2025-01-06  │
│          ┆              ┆ kámen -      ┆              ┆   ┆ ull,null,nul ┆ 4:32","19:4 ┆ Martin      ┆ 23:38:34    │
│          ┆              ┆ Velká Skála  ┆              ┆   ┆ l,0}         ┆ 5",{"str…   ┆ Grünwald    ┆ CET         │
│          ┆              ┆              ┆              ┆   ┆              ┆             ┆ jun…        ┆             │
└──────────┴──────────────┴──────────────┴──────────────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [181]:
df.filter(pl.col('country').str.contains('Cze')).filter(pl.col('activity_type') == 'Run').group_by("name").agg(pl.col('effort_count').cast(int).max()).sort(by='effort_count',descending=True).head(n=10)

shape: (10, 2)
┌─────────────────────────────────┬──────────────┐
│ name                            ┆ effort_count │
│ ---                             ┆ ---          │
│ str                             ┆ i64          │
╞═════════════════════════════════╪══════════════╡
│ Stadion Na Děkance              ┆ 215619       │
│ Lužánky rovinka                 ┆ 180145       │
│ Šlechtovka - finální rovinka    ┆ 156359       │
│ VUT horní dráha 400m            ┆ 109048       │
│ Vítkov up sprint                ┆ 86621        │
│ Pražačka 320                    ┆ 75242        │
│ TJ Sokol okruh                  ┆ 72849        │
│ Kolo na stadionu v Třebíči      ┆ 69590        │
│ 400 m - atletický okruh - Loko… ┆ 52422        │
│ Hvězda flat                     ┆ 49909        │
└─────────────────────────────────┴──────────────┘

In [75]:
pl.Series(df.select("name")).to_list()

['Dlouhe Strane od Loucnej',
 'Lysa hora - jizni sjezdovka',
 'Kvilda Bučina',
 'Od dubu ke Gizele',
 'Risova studanka - od zavory',
 'Bečva - Pustevny Uphill',
 'Židlochovice -> Olympia',
 'Pavlov - Dívčí hrad climb',
 'Nová cyklostezka do Bosche  2',
 'Tuhnická lávka -Chebský most',
 'Šup do parku',
 'Szpic Jested  last 3 km ( od rozc na Dub)',
 'Lužánky rovinka',
 'Snezka po schodech',
 'Dlouhe Strane od Loucnej',
 'Hvězda flat',
 'Od letňáku ke starému vchodu ZOO',
 'Maslovice - Kralupy',
 'Opičí Časovka, Podolská vodárna - Dvorce',
 'Smetanovy reverse',
 'tenis 1K',
 'Klinovec Top',
 'Štvanická lávka (do Karlína)',
 'time trial at Svratka',
 'Tuhnice most-Drahovice most,stezka',
 'mezi mosty',
 'Šlechtovka - finální rovinka',
 'Tygří výzva, sklon 32% :)',
 'Park 1',
 'Jiráskovo nábřeží k Husovce',
 'Zbraslav - Komořany',
 'Lysa hora - jizni sjezdovka',
 'Opavska down 1/2',
 'Červená podél Zlaté stoky do Třeboně',
 'Podél tratě do Úval',
 'od hráze až na konec přehrady - silnice',
 'Interval ',
 'Zweite hup u ZOO',
 'Kolem stadionu',
 'Sedýlko - Praděd climb',
 'Od dubu ke Gizele',
 'Junglepark',
 '400 metrů, 44 120 diváků',
 'Lysá hora - 5 km',
 'Kvilda Bučina',
 'Od dubu ke Gizele',
 'hurá na Říp',
 'time trial at Svratka',
 'Luisino údolí - Velká Deštná',
 'Lysa hora - jizni sjezdovka',
 'Sněžník od Děčína (po červené)',
 'Maslovice - Kralupy',
 'od hráze až na konec přehrady - silnice',
 'segment z Tábora',
 'Pláně - Černý vrch',
 'Karlův most ONLY',
 'Říp po žluté na vyhlídku',
 'Bečva - Pustevny Uphill',
 'Snezka po schodech',
 'Mutěnka - z Kyjova po odbočku na hraběcí',
 'Od posledního tunelu do Bílovic',
 'Bludička-Opavice',
 'Posázavskou k odbočce před schody',
 'Do sedla Klínovce po silnici',
 '15% Stoupák Bártlovka->Paličník',
 'Karlov - k Velkému kotli',
 'Tři prameny - Pravčická brána',
 'Ostaš',
 'Podle Radbuzy',
 'Benedikt - Parkoviště',
 'Podél tratě do Úval',
 'Opičí Časovka, Podolská vodárna - Dvorce',
 'Kolem stadionu',
 'Videlské sedlo-Švýcárna',
 'Štvanická lávka (do Karlína)',
 'Šlechtovka - finální rovinka',
 'kopec na hrad',
 'U Jordánu do kopce',
 'Solan last km',
 'Luční bouda - Sněžka',
 'Výpřež - Ještěd (po červené)',
 'Železniční most => Jez Vítkovice',
 'Tygří výzva, sklon 32% :)',
 'Dlouhe Strane od Loucnej',
 'Srbsko - Hlásná Třebáň',
 'Dneboh - Drábské Světničky',
 'Lacinův kámen - Velká Skála',
 'Kraličák Skyrace - 2. kopec',
 'Hadí stezka na Svatobor 🐍',
 'Červená voda - Suchý vrch',
 'Okolo Bobrůvky Tři Studně - Koupaliště NMNM',
 'Junglepark',
 'Šobes - sjezd',
 'Park 1',
 'Cyklostezka Náchod -> Velké Poříčí',
 'Ručičky - Krakonošova snídaně (po žluté)',
 'Kerhartice-Choceň',
 'Cyklostezka Stará huť-Dobříš',
 'Ruda -> Gerlovka',
 'Szpic Jested  last 3 km ( od rozc na Dub)',
 'Ježánky(Visalaje) - Bílý Kříž (směr Visalaje)',
 'Hoštejn-Zábřeh',
 'Nová cyklostezka do Bosche  2',
 'Opavska down 1/2',
 'Ořešník',
 'Zbraslav - Komořany',
 'Kočičí žleb - Ríšova studánka',
 '611 - Mstetice',
 'Tuhnická lávka -Chebský most',
 'Borůvková hora part II',
 'Bunč climb',
 'Revnicak Eve',
 'Židlochovice -> Olympia',
 'Šárka Valley (short)',
 'Klinovec Top',
 'Obří hřeben - stoupák',
 'Kleť k vysílači - finále',
 'Hadí stezka (Svatobor)',
 'Zlaťák konec - smrt',
 'Výrovka - Modré Sedlo',
 'Interval ',
 'Debř-Michalovice ☠',
 'Lysá hora - 5 km',
 'Javorový od stanice lanovky',
 'Od letňáku ke starému vchodu ZOO',
 'Kvilda Bučina',
 'Sjezd Blatno-Březenec',
 'Po červené na Předěl',
 'Stojka na Pancíř',
 'Richtrovy boudy - Výrovka',
 'Most Legií (směr Kampa)',
 'Lednice - Bulhary',
 'Transformator k Butorance (u studanky)',
 'Sedýlko - Praděd climb',
 'Malchor - Lysá Hora',
 'Pavlov - Dívčí hrad climb',
 'Lužánky rovinka',
 'Šup do parku',
 'Špindlerův Mlýn - Školní',
 'Smetanovy reverse',
 'Kynšperský ATAK ',
 'Čerťák - Ručičky (po modré)',
 'Risova studanka - od zavory',
 'Stoupání na Templštejn',
 'Hrad Vevěří - Hráz',
 'Pod Vilemínkou - Kralický Sněžník (žlutá)',
 'Bečva - Pustevny Uphill',
 'hurá na Říp',
 'Štvanická lávka (do Karlína)',
 'Karlův most ONLY',
 'Okolo Bobrůvky Tři Studně - Koupaliště NMNM',
 'Nová cyklopěšina z Peřiny do HTčka',
 'Jiráskovo nábřeží k Husovce',
 'Šup do parku',
 'Kleť k vysílači - finále',
 'Harusák Climb',
 'time trial at Svratka',
 'Pláně - Černý vrch',
 'BL Boletice - rovinka na hřebeni',
 'Hrad Vevěří - Hráz',
 'Zbraslav - Komořany',
 'Špindlerův Mlýn - Školní',
 'Revnicak Eve',
 'Kynšperský ATAK ',
 'Lysá hora - 5 km',
 'Daskabát flat',
 'Nové Lesy-Dvůr Králové',
 'Karlov - k Velkému kotli',
 'Maslovice - Kralupy',
 'Cyklostezka sprint směr Děčín',
 'Šumbera pom. odb. - vysílač Hády',
 'Risova studanka - od zavory',
 'tenis 1K',
 'Podle Radbuzy',
 'Kerhartice-Choceň',
 'Hadí stezka (Svatobor)',
 'Zig-zag na Šerák',
 'Červená voda - Suchý vrch',
 'Pec - Sněžka (přes Obřák)',
 'Dlouhe Strane od Loucnej',
 'Lednice - Bulhary',
 'Kozí hřbety - Luční bouda',
 'Rovinka Beranov',
 'Sedýlko - Praděd climb',
 'Hradní lávka => Sýkorův most',
 'Říp po žluté na vyhlídku',
 'Kleť',
 'Bunč climb',
 'Šantovka - Kojeňák',
 'Kolem stadionu',
 'Most Legií (směr Kampa)',
 'Výrovka - Modré Sedlo',
 'plný kule z kolína',
 'Cyklostezka Stará huť-Dobříš',
 'Srbsko - Hlásná Třebáň',
 'Špindlerovka - část II. (od Černýho potoka nahoru)',
 'Richtrovy boudy - Výrovka',
 'Čerťák - Ručičky (po modré)',
 'Sjezd Blatno-Březenec',
 'mezi mosty',
 'Šárka Valley (short)',
 'Tři prameny - Pravčická brána',
 '611 - Mstetice',
 'Ježánky(Visalaje) - Bílý Kříž (směr Visalaje)',
 'Stojka na Pancíř',
 'Hvězda flat',
 'Sněžník od Děčína (po červené)',
 'Ruda -> Gerlovka',
 'stezka',
 'Trinec-Tesin',
 'segment z Tábora',
 'Nová cyklostezka do Bosche  2',
 'Po červené na Předěl',
 'Posázavskou k odbočce před schody',
 'Dneboh - Drábské Světničky',
 'Výpřež - Ještěd (po červené)',
 'Snezka po schodech',
 'Svaty kopecek up',
 'Smetanovy reverse',
 'podle Labe do Týnce',
 'Do sedla Klínovce po silnici',
 'Borůvková hora part II',
 'Kočičí žleb - Ríšova studánka',
 'Třebíč - Stařeč po cyklostezce (LS)',
 'Okruhy Ochozou - Výběh na Harusák (0,76 km / 105 m)',
 'Stoupání na Templštejn',
 'Pod Homoli Climb',
 'Benedikt - Parkoviště',
 'Židlochovice -> Olympia',
 'Malchor - Lysá Hora',
 'Železniční most => Jez Vítkovice',
 'Videlské sedlo-Švýcárna',
 'Pavlov - Dívčí hrad climb',
 'Od bývalé sáňkařské dráhy po modré na Ještěd',
 'Javorový od stanice lanovky',
 'Lysa hora - jizni sjezdovka',
 'Od posledního tunelu do Bílovic',
 'Soláň-Tanečnica',
 'Ručičky - Krakonošova snídaně (po žluté)',
 'Park 1',
 'Kraličák Skyrace - 2. kopec',
 'Ostaš',
 'Od letňáku ke starému vchodu ZOO',
 'Stezka nábřeží',
 'svadov—valtirov',
 'Ostaš',
 'Od letňáku ke starému vchodu ZOO',
 'Od bývalé sáňkařské dráhy po modré na Ještěd',
 'Špindlerovka - část II. (od Černýho potoka nahoru)',
 'Kynšperský ATAK ',
 'Podél dálnice',
 'Lacinův kámen - Velká Skála',
 'Sedýlko - Praděd climb',
 'Kleť',
 'Židlochovice -> Olympia',
 'Cyklostezka Náchod -> Velké Poříčí',
 'Ořešník',
 'Šup do parku',
 'Zlaťák konec - smrt',
 'Hrad Vevěří - Hráz',
 'od hráze až na konec přehrady - silnice',
 'Lužánky rovinka',
 'Nová cyklostezka do Bosche  2',
 'Modrava - Tříjezerní slať',
 'hurá na Říp',
 'Jiráskovo nábřeží k Husovce',
 'kopec na hrad',
 'Daskabát flat',
 'Harusák Climb',
 'Špindlerův Mlýn - Školní',
 'Posázavskou k odbočce před schody',
 'Lysa hora - jizni sjezdovka',
 'Sjezd Blatno-Březenec',
 'Dlouhe Strane od Loucnej',
 'Ježánky(Visalaje) - Bílý Kříž (směr Visalaje)',
 'Výrovka - Modré Sedlo',
 'Muglinovská→Hradní lávka (po pravém břehu)',
 'Bečva - Pustevny Uphill',
 'Stojka na Pancíř',
 'Železniční most => Jez Vítkovice',
 'Soláň-Tanečnica',
 'Tuhnická lávka -Chebský most',
 'Neklid -> Klínovec',
 'Kvilda Bučina',
 '611 - Mstetice',
 'Papezov - Prazmo ',
 'Stezka nábřeží',
 'Do sedla Klínovce po silnici',
 'Dneboh - Drábské Světničky',
 'Lysá hora - 5 km',
 'Pláně - Černý vrch',
 'Benešovský brdek',
 'Videlské sedlo-Švýcárna',
 'Ruda -> Gerlovka',
 'Kerhartice-Choceň',
 'Třebíč - Stařeč po cyklostezce (LS)',
 'Benedikt - Parkoviště',
 'Junglepark',
 'stezka',
 'JestedSkyrace - last uphill - middle part',
 'Nové Lesy-Dvůr Králové',
 'Borůvková hora part II',
 'Szpic Jested  last 3 km ( od rozc na Dub)',
 'Hadí stezka na Svatobor 🐍',
 'Srbsko - Hlásná Třebáň',
 '15% Stoupák Bártlovka->Paličník',
 'Podél tratě do Úval',
 'Kolem stadionu',
 'Most Legií (směr Kampa)',
 'Říp po žluté na vyhlídku',
 'Tři prameny - Pravčická brána',
 'svadov—valtirov',
 'Čerťák - Ručičky (po modré)',
 'Park 1',
 'Pod Vilemínkou - Kralický Sněžník (žlutá)',
 'Klinovec Top',
 'Rovinka Beranov',
 'TJ Sokol okruh',
 'Malchor - Lysá Hora',
 'Luční bouda - Sněžka',
 'Obří hřeben - stoupák',
 'Trinec-Tesin',
 'Od posledního tunelu do Bílovic',
 'Richtrovy boudy - Výrovka',
 'Svaty kopecek up',
 'Karlův most ONLY',
 'Transformator k Butorance (u studanky)',
 'Solan last km',
 'Tuhnice most-Drahovice most,stezka',
 'Opavska down 1/2',
 'Tříjezerní slať - Rokyta',
 'Pod Homoli Climb',
 'Interval ',
 'Zweite hup u ZOO',
 'Nová cyklopěšina z Peřiny do HTčka',
 'Ručičky - Krakonošova snídaně (po žluté)',
 'Kraličák Skyrace - 2. kopec',
 'Stoupání na Templštejn',
 'Revnicak Eve',
 'U Jordánu do kopce',
 'Pustevny - Radhošť',
 'Hlavní třídou nahoru',
 'Sněžník od Děčína (po červené)',
 'Pavlov - Dívčí hrad climb',
 'Hadí stezka (Svatobor)',
 'Interval ',
 'svadov—valtirov',
 'Dlouhe Strane od Loucnej',
 'Bludička-Opavice',
 'Hradiště - čtyřstovka',
 'Javorový od stanice lanovky',
 'Nová cyklopěšina z Peřiny do HTčka',
 'Stezka do Zlina',
 'Zbraslav - Komořany',
 'Videlské sedlo-Švýcárna',
 'Obří hřeben - stoupák',
 'Pražačka 320',
 'Hradní lávka => Sýkorův most',
 'Sněžník od Děčína (po červené)',
 'Kraličák Skyrace - 2. kopec',
 'BL Boletice - rovinka na hřebeni',
 'Šumbera pom. odb. - vysílač Hády',
 'Valy',
 'Rybnik',
 'Čerťák - Ručičky (po modré)',
 '611 - Mstetice',
 'Zweite hup u ZOO',
 'Podle Radbuzy',
 'Okruhy Ochozou - Výběh na Harusák (0,76 km / 105 m)',
 'Máchovo kritérium - přes bory kolem vrchu Borný',
 'Cyklostezka Stará huť-Dobříš',
 'Od bývalé sáňkařské dráhy po modré na Ještěd',
 'Pod Homoli Climb',
 'Karlov - k Velkému kotli',
 'Most Legií (směr Kampa)',
 'Červená voda - Suchý vrch',
 'TJ Sokol okruh',
 'most - Loket',
 'tenis 1K',
 'Kvilda Bučina',
 'Kleť k vysílači - finále',
 'Zig-zag na Šerák',
 'Tuhnice most-Drahovice most,stezka',
 'Solan last km',
 'Židlochovice -> Olympia',
 'Malchor - Lysá Hora',
 'Plácky-soutok',
 'do Srní',
 'Červená podél Zlaté stoky do Třeboně',
 'Po červené na Předěl',
 'time trial at Svratka',
 'Svaty kopecek up',
 'Údolí Svatý Jan',
 'Kopeček - od kruháče k bazilice',
 'Stezka nábřeží',
 'Kočičí žleb - Ríšova studánka',
 'Sedýlko - Praděd climb',
 'Muglinovská→Hradní lávka (po pravém břehu)',
 'Šlechtovka - finální rovinka',
 'kopec na hrad',
 'Do sedla Klínovce po silnici',
 'Tuhnická lávka -Chebský most',
 'Štvanická lávka (do Karlína)',
 'Luby end',
 'Rovinka Beranov',
 'Lysa hora - jizni sjezdovka',
 'stezka',
 'Karlův most ONLY',
 '400m',
 'Luční bouda - Sněžka',
 '15% Stoupák Bártlovka->Paličník',
 'Cyklostezka sprint směr Děčín',
 'Javorník finish od Pinduly',
 'Jiráskovo nábřeží k Husovce',
 'Hostyn-od.zastavky.po.znacku.P',
 'Harusák Climb',
 'Okolo Bobrůvky Tři Studně - Koupaliště NMNM',
 'Tříjezerní slať - Rokyta',
 'Daskabát flat',
 'Pod Vilemínkou - Kralický Sněžník (žlutá)',
 'Hoštejn-Zábřeh',
 'stupani k vetr. mlynu Kuzelov',
 'Borůvková hora part II',
 'Tygří výzva, sklon 32% :)',
 'Ruda -> Gerlovka',
 'Kleť',
 'Starý Kolín - Svatá Kateřina',
 'Výpřež - Ještěd (po červené)',
 'Opičí Časovka, Podolská vodárna - Dvorce',
 'Ondřejník sedlo - Ondřejník vrchol',
 'Zrucskej smrtak',
 'Trinec-Tesin',
 'segment z Tábora',
 'VR #11 finish',
 'Park 1',
 'Lysá hora - 5 km',
 'Risova studanka - od zavory',
 'Černý důl konec Hoffmanky',
 'Cyklostezka Náchod -> Velké Poříčí',
 'Total brikule 🚀',
 'Třebíč - Stařeč po cyklostezce (LS)',
 'plný kule z kolína',
 'Soláň-Tanečnica',
 'Pustevny - Radhošť',
 'Hadí stezka na Svatobor 🐍',
 'Bunč climb',
 'Chrudim climb',
 '400 m - atletický okruh - Lokomotiva',
 'Neklid -> Klínovec',
 'Lednice - Bulhary',
 'Snezka po schodech',
 'Kopec pod Barborou',
 'od hráze až na konec přehrady - silnice',
 'JestedSkyrace - last uphill - middle part',
 'Benedikt - Parkoviště',
 'Kuželna - Splav 800m',
 'Stoupání na Templštejn',
 'Jesenice-Blatno DH',
 'Srbsko - Hlásná Třebáň',
 'Opavska down 1/2',
 'Transformator k Butorance (u studanky)',
 'Šup do parku',
 'podle Labe do Týnce',
 'Sjezd Blatno-Březenec',
 'Stadion Na Děkance',
 'Šárka Valley (short)',
 'Sptint pod Býčí skálou',
 'Mutěnka - z Kyjova po odbočku na hraběcí',
 '400 metrů, 44 120 diváků',
 'Podél tratě do Úval',
 'Kolem stadionu',
 'Le Grande Classico',
 'Eurovie - nadjezd Rosice',
 'Benešovský brdek',
 'Pisek podel reky I',
 'Ořešník',
 'Klinovec Top',
 'Ježánky(Visalaje) - Bílý Kříž (směr Visalaje)',
 'U Jordánu do kopce',
 '#ULhalf - Strekovske Nabrezi',
 'Ovál ZŠ Štefánikova',
 'Ostaš',
 'Pavlov - Dívčí hrad climb',
 'Lužánky rovinka',
 'Od letňáku ke starému vchodu ZOO',
 'mezi mosty',
 'Hrad Vevěří - Hráz',
 'Hlavní třídou nahoru',
 'Lužánky - Plochá dráha',
 'Debř-Michalovice ☠',
 'MH - Klaster',
 'Od posledního tunelu do Bílovic',
 'Ručičky - Krakonošova snídaně (po žluté)',
 'Pec - Sněžka (přes Obřák)',
 'hurá na Říp',
 'Bečva - Pustevny Uphill',
 'Vlevo dole jezero Most',
 'Decin - Bad Schandau Abzweig Radwg',
 'Pláně - Černý vrch',
 'Smetanovy reverse',
 'Nová cyklostezka do Bosche  2',
 'Tři prameny - Pravčická brána',
 'Sedmička, Lipno {',
 'Kynšperský ATAK ',
 'Lacinův kámen - Velká Skála',
 'Hvězda flat',
 'Junglepark',
 'Vojenský ovál 400M',
 'Špindlerovka - část II. (od Černýho potoka nahoru)',
 'Revnicak Eve',
 'Maslovice - Kralupy',
 'Výrovka - Modré Sedlo',
 'Hadí stezka (Svatobor)',
 'Posázavskou k odbočce před schody',
 'Giro di Tyrš',
 'VUT horní dráha 400m',
 'Kozí hřbety - Luční bouda',
 'Železniční most => Jez Vítkovice',
 'Říp po žluté na vyhlídku',
 'Szpic Jested  last 3 km ( od rozc na Dub)',
 'Šobes - sjezd',
 'Nové Lesy-Dvůr Králové',
 'Zlaťák konec - smrt',
 'Šantovka - Kojeňák',
 'Modrava - Tříjezerní slať',
 'Dneboh - Drábské Světničky',
 'Juliska 400 m',
 'Pod rozhlednu Babi lom',
 'Panelovka-Tichá 800m',
 'Od dubu ke Gizele',
 'Kaufland - Popendorf ',
 'Richtrovy boudy - Výrovka',
 'Stojka na Pancíř',
 'Luisino údolí - Velká Deštná',
 'Podél dálnice',
 'Krkonošská',
 'Ku řopíku',
 'Špindlerův Mlýn - Školní',
 'Kerhartice-Choceň',
 'Papezov - Prazmo ',
 'k přehradě hop',
 'Benedikt - Parkoviště',
 'Bludička-Opavice',
 'Lípy (směrem do Jičína)',
 'Zbraslav - Komořany',
 'Od křižovatky do Strání po vysílač',
 'Od lávky k lávce',
 'Segment',
 'Kozí hřbety - Luční bouda',
 'Od letňáku ke starému vchodu ZOO',
 'S&Ch20 Masarykův okruh',
 'Rybnik',
 'Šárka Valley (short)',
 'kopec na hrad',
 'Most - Most -> Břeclav',
 'Hlavní třídou nahoru',
 'Jiráskovo nábřeží k Husovce',
 'U Jordánu do kopce',
 'Čerťák - Ručičky (po modré)',
 'Hradní lávka => Sýkorův most',
 'Borůvková hora part II',
 'Rovinka Beranov',
 'Sa Calobra - Coll dels Reis',
 'Nová cyklostezka do Bosche  2',
 '400 m (track num. 2)',
 'Pustevny - Radhošť',
 'Solan last km',
 'Ručičky - Krakonošova snídaně (po žluté)',
 'Pec - Sněžka (přes Obřák)',
 'Tyršák čtyřstofka',
 "Alpe d'Huez",
 'Ruda -> Gerlovka',
 'Z Doubravky k Josefu',
 'Posázavskou k odbočce před schody',
 'Hoštejn-Zábřeh',
 'TJ Sokol okruh',
 'Od bývalé sáňkařské dráhy po modré na Ještěd',
 '#ULhalf - Strekovske Nabrezi',
 'Stoupání na Templštejn',
 'Špindlerovka - část II. (od Černýho potoka nahoru)',
 'Kolo na stadionu v Třebíči',
 'Ciclo Via BNL -> K',
 'Total brikule 🚀',
 'panelka k bráně ˇerchova',
 'Kraličák Skyrace - 2. kopec',
 'plný kule z kolína',
 'Opavska down 1/2',
 'Track Domažlice',
 'MH - Klaster',
 'Stojka na Pancíř',
 'Starý Kolín - Svatá Kateřina',
 'Die Eine Runde',
 'Železniční most => Jez Vítkovice',
 'Transformator k Butorance (u studanky)',
 'tenis 1K',
 'Labe_po asfaltu',
 'Rovinka od kruháče k bazénu',
 'Viveros-Paseo alameda',
 'Pavlov - Dívčí hrad climb',
 'Stezka nábřeží',
 'k přehradě hop',
 'Szlak czerwony, Schronisko Nad Łomniczką - Dom Śląski',
 'Sedýlko - Praděd climb',
 'Juliska 400 m',
 'Zlaťák konec - smrt',
 'Col du Tourmalet (par Luz-St-Sauveur)',
 'Malchor - Lysá Hora',
 '400m-Jičín',
 'Passo Stelvio',
 'VUT horní dráha 400m',
 'Plácky-soutok',
 'Od Sanusu ke gymplu',
 'Javorník finish od Pinduly',
 'Červená voda - Suchý vrch',
 'Šobes - sjezd',
 'Cyklostezka Náchod -> Velké Poříčí',
 '15% Stoupák Bártlovka->Paličník',
 'Štvanická lávka (do Karlína)',
 'Stezka do Zlina',
 'Most Legií (směr Kampa)',
 'Lysá hora - 5 km',
 'Nové Lesy-Dvůr Králové',
 '2012 Pikes Peak Hill Climb',
 'Mutěnka - z Kyjova po odbočku na hraběcí',
 'Berounka sprint',
 'Harusák Climb',
 'Kopec pod Barborou',
 'Decin - Bad Schandau Abzweig Radwg',
 'Luční bouda - Sněžka',
 'Dneboh - Drábské Světničky',
 'Snezka po schodech',
 'Soláň-Tanečnica',
 'Luisino údolí - Velká Deštná',
 'Karlův most ONLY',
 'Adamaov climb',
 'Ovál ZŠ Štefánikova',
 'Javorový od stanice lanovky',
 'Svaty kopecek up',
 'Hrad Vevěří - Hráz',
 'Papezov - Prazmo ',
 'Junglepark',
 'Neklid -> Klínovec',
 'Trinec-Tesin',
 'Sedmička, Lipno {',
 'Opavice od zatáčky',
 'Bečva - Pustevny Uphill',
 'Sprint Páteček - Santos',
 'Po červené na Předěl',
 'Klinovec Top',
 'Tatran Třemošná',
 'Cyklostezka sprint směr Děčín',
 'Ještěd Finale konec před kostkami. ',
 'Kynšperský ATAK ',
 'Eurovie - nadjezd Rosice',
 'Krkonošská',
 'Gránické údolí - Central Part DOWN',
 '400m - Sportovní areál Na Stoupách',
 'Ježánky(Visalaje) - Bílý Kříž (směr Visalaje)',
 'Stodůlecký - Nepomucký rybník',
 'Lednice - Bulhary',
 'Šlechtovka - finální rovinka',
 'Koupaliště sprint',
 'Opičí Časovka, Podolská vodárna - Dvorce',
 'Muglinovská→Hradní lávka (po pravém břehu)',
 'Šumbera pom. odb. - vysílač Hády',
 'Kočičí žleb - Ríšova studánka',
 'TJ Znojmo Lap',
 'Ořešník',
 'Podle Radbuzy',
 'mezi mosty',
 'Szpic Jested  last 3 km ( od rozc na Dub)',
 'LS - Park Boost',
 'Mezi zábranama (proti proudu)',
 'most - Loket',
 'Sjezd Blatno-Březenec',
 'Karlov - k Velkému kotli',
 'Kolem stadionu',
 'Interval ',
 'Máchovo kritérium - přes bory kolem vrchu Borný',
 'Špindlerův Mlýn - Školní',
 'Box Hill 2.2k',
 'Okruhy Ochozou - Výběh na Harusák (0,76 km / 105 m)',
 'hurá na Říp',
 'do Srní',
 'Šantovka - Kojeňák',
 'Sptint pod Býčí skálou',
 'rovinka kolem Sázavy:Plynovod-křižovatka u Mostu',
 'Dlouhe Strane od Loucnej',
 'Pláně - Černý vrch',
 'Kuželna - Splav 800m',
 'Lužánky - Plochá dráha',
 'Hilo to Mauna Kea',
 'Valy',
 'podél Podměstského rybníku',
 'Smetanovy reverse',
 '400m',
 'svadov—valtirov',
 'Údolí Svatý Jan',
 'Výrovka - Modré Sedlo',
 'Le Grande Classico',
 'Ostaš',
 'Tuhnice most-Drahovice most,stezka',
 'Tříjezerní slať - Rokyta',
 'Benešovský brdek',
 'Dom Śląski Up Hill',
 'Modrava - Tříjezerní slať',
 'Videlské sedlo-Švýcárna',
 'Vítkov up sprint ',
 'Podél dálnice',
 'VR #11 finish',
 'Do sedla Klínovce po silnici',
 'Od dubu ke Gizele',
 'Ku řopíku',
 'Zweite hup u ZOO',
 'Richtrovy boudy - Výrovka',
 'Tygří výzva, sklon 32% :)',
 'Výstup na Klínovec',
 'Kaufland - Popendorf ',
 'Lacinův kámen - Velká Skála',
 'Černý důl konec Hoffmanky',
 'Dráha Plzeň okruh P',
 'Židlochovice -> Olympia',
 'Richmond ITT1',
 'Mont Ventoux (par Bedoin)',
 'Stelvio - Bormio Turn Downhill',
 'podle Labe do Týnce',
 'Overtake the Boris Bikes',
 'time trial at Svratka',
 'JestedSkyrace - last uphill - middle part',
 'Pod rozhlednu Babi lom',
 'Kleť',
 'Bunč climb',
 'Kerhartice-Choceň',
 'Sněžník od Děčína (po červené)',
 'stezka',
 'Ondřejník sedlo - Ondřejník vrchol',
 '400 m - atletický okruh - Lokomotiva',
 'Kvilda Bučina',
 'Velodrom 1kolo',
 'Prostějov kolo dráha P',
 'Srbsko - Hlásná Třebáň',
 'Debř-Michalovice ☠',
 '611 - Mstetice',
 'Od posledního tunelu do Bílovic',
 'Rokytka od myčky',
 'Červená podél Zlaté stoky do Třeboně',

In [ ]:
df.group_by_dynamic("date", by="name", every="1d").agg(pl.col("effort_count").max())

In [111]:
import altair as alt

In [179]:
segm = df.filter(pl.col('name') == 'Vojenský ovál 400M').group_by_dynamic("date", every="1d").agg(pl.col("effort_count").max())
segm = segm.with_columns(pl.col("effort_count").diff().alias("daily_difference")).drop_nulls()
segm = segm.with_columns(pl.col("date").cast(str))
alt.Chart(segm).mark_bar().encode(
    x='date:O',
    y='daily_difference:Q'
)

alt.Chart(...)

In [195]:
df = pl.read_parquet('data/segments.parquet')

In [193]:
df

shape: (3_410, 17)
┌──────────┬───────────────┬──────────────┬──────────┬───┬──────────────┬──────────────┬──────────────┬──────────────┐
│ id       ┆ name          ┆ activity_typ ┆ distance ┆ … ┆ effort_count ┆ athlete_coun ┆ date         ┆ start_to_fin │
│ ---      ┆ ---           ┆ e            ┆ ---      ┆   ┆ ---          ┆ t            ┆ ---          ┆ ish_distance │
│ i64      ┆ str           ┆ ---          ┆ f64      ┆   ┆ i64          ┆ ---          ┆ datetime[μs, ┆ ---          │
│          ┆               ┆ str          ┆          ┆   ┆              ┆ i64          ┆ CET]         ┆ f64          │
╞══════════╪═══════════════╪══════════════╪══════════╪═══╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 10186045 ┆ Opičí         ┆ Ride         ┆ 1390.1   ┆ … ┆ 322708       ┆ 16496        ┆ 2024-12-24   ┆ 1.379737     │
│          ┆ Časovka,      ┆              ┆          ┆   ┆              ┆              ┆ 23:05:07 CET ┆              │
│          ┆ Podolská      ┆              ┆          ┆   ┆              ┆              ┆              ┆              │
│          ┆ vodárn…       ┆              ┆          ┆   ┆              ┆              ┆              ┆              │
│ 10356069 ┆ Kvilda Bučina ┆ Ride         ┆ 5645.6   ┆ … ┆ 5604         ┆ 1683         ┆ 2024-12-24   ┆ 5.008856     │
│          ┆               ┆              ┆          ┆   ┆              ┆              ┆ 23:02:12 CET ┆              │
│ 10356069 ┆ Kvilda Bučina ┆ Ride         ┆ 5645.6   ┆ … ┆ 5604         ┆ 1683         ┆ 2024-12-24   ┆ 5.008856     │
│          ┆               ┆              ┆          ┆   ┆              ┆              ┆ 23:05:14 CET ┆              │
│ 11378514 ┆ Park 1        ┆ Run          ┆ 718.9    ┆ … ┆ 13560        ┆ 2293         ┆ 2024-12-24   ┆ 0.699398     │
│          ┆               ┆              ┆          ┆   ┆              ┆              ┆ 23:05:10 CET ┆              │
│ 11490813 ┆ Interval      ┆ Run          ┆ 848.8    ┆ … ┆ 5864         ┆ 792          ┆ 2024-12-24   ┆ 0.822266     │
│          ┆               ┆              ┆          ┆   ┆              ┆              ┆ 23:05:12 CET ┆              │
│ …        ┆ …             ┆ …            ┆ …        ┆ … ┆ …            ┆ …            ┆ …            ┆ …            │
│ 9125491  ┆ Daskabát flat ┆ Ride         ┆ 1868.0   ┆ … ┆ 10016        ┆ 1351         ┆ 2025-01-06   ┆ 1.853476     │
│          ┆               ┆              ┆          ┆   ┆              ┆              ┆ 23:05:22 CET ┆              │
│ 9153928  ┆ Sprintík křiž ┆ Ride         ┆ 3075.3   ┆ … ┆ 30470        ┆ 3207         ┆ 2025-01-06   ┆ 2.099472     │
│          ┆ ovatka/skalní ┆              ┆          ┆   ┆              ┆              ┆ 23:21:41 CET ┆              │
│          ┆ mlý…          ┆              ┆          ┆   ┆              ┆              ┆              ┆              │
│ 9433317  ┆ Třebešín-dráh ┆ Ride         ┆ 347.2    ┆ … ┆ 402245       ┆ 334          ┆ 2025-01-06   ┆ 0.008769     │
│          ┆ a K           ┆              ┆          ┆   ┆              ┆              ┆ 23:05:29 CET ┆              │
│ 9458674  ┆ Zrucskej      ┆ Ride         ┆ 732.4    ┆ … ┆ 1334         ┆ 760          ┆ 2025-01-06   ┆ 0.425948     │
│          ┆ smrtak        ┆              ┆          ┆   ┆              ┆              ┆ 23:38:28 CET ┆              │
│ 9959344  ┆ time trial at ┆ Ride         ┆ 1438.1   ┆ … ┆ 141864       ┆ 9372         ┆ 2025-01-06   ┆ 1.300465     │
│          ┆ Svratka       ┆              ┆          ┆   ┆              ┆              ┆ 23:22:06 CET ┆              │
└──────────┴───────────────┴──────────────┴──────────┴───┴──────────────┴──────────────┴──────────────┴──────────────┘