In [1]:
import os
import polars as pl
import altair as alt

In [2]:
csvs = [x for x in os.listdir('data_raw') if 'time_series_CZ_' in x]

df = pl.DataFrame()
for csv in csvs:
    df = pl.concat(
        [
            df,
            pl.read_csv(os.path.join("data_raw",csv)).unpivot(index='Time').with_columns(pl.col('Time').str.to_date())
        ]
    )

In [3]:
df

shape: (2_634, 3)
┌────────────┬──────────┬───────┐
│ Time       ┆ variable ┆ value │
│ ---        ┆ ---      ┆ ---   │
│ date       ┆ str      ┆ i64   │
╞════════════╪══════════╪═══════╡
│ 2004-01-01 ┆ běhání   ┆ 0     │
│ 2004-02-01 ┆ běhání   ┆ 0     │
│ 2004-03-01 ┆ běhání   ┆ 0     │
│ 2004-04-01 ┆ běhání   ┆ 0     │
│ 2004-05-01 ┆ běhání   ┆ 0     │
│ …          ┆ …        ┆ …     │
│ 2025-10-01 ┆ VO2 max  ┆ 50    │
│ 2025-11-01 ┆ VO2 max  ┆ 55    │
│ 2025-12-01 ┆ VO2 max  ┆ 41    │
│ 2026-01-01 ┆ VO2 max  ┆ 53    │
│ 2026-02-01 ┆ VO2 max  ┆ 67    │
└────────────┴──────────┴───────┘

In [4]:
df.group_by(pl.col('Time').dt.month()).agg(pl.col('value').median()).sort(by='Time')

shape: (12, 2)
┌──────┬───────┐
│ Time ┆ value │
│ ---  ┆ ---   │
│ i8   ┆ f64   │
╞══════╪═══════╡
│ 1    ┆ 11.0  │
│ 2    ┆ 14.0  │
│ 3    ┆ 25.0  │
│ 4    ┆ 33.0  │
│ 5    ┆ 36.5  │
│ …    ┆ …     │
│ 8    ┆ 37.0  │
│ 9    ┆ 22.0  │
│ 10   ┆ 13.0  │
│ 11   ┆ 12.0  │
│ 12   ┆ 10.5  │
└──────┴───────┘

In [5]:
alt.Chart(
    df.filter(pl.col('variable') == "jak začít běhat").group_by(pl.col('Time').dt.month()).agg(pl.col('value').median()).sort(by='Time')
).mark_bar(
).encode(
    alt.X('Time:N'),
    alt.Y('value:Q')
)

alt.Chart(...)

In [6]:
alt.Chart(
    df.filter(pl.col('variable') == "boty na běhání").group_by(pl.col('Time').dt.month()).agg(pl.col('value').median()).sort(by='Time')
).mark_bar(
).encode(
    alt.X('Time:N'),
    alt.Y('value:Q')
)

alt.Chart(...)

In [7]:
alt.Chart(
    df.filter(pl.col('variable') == "běhání").group_by(pl.col('Time').dt.month()).agg(pl.col('value').median()).sort(by='Time')
).mark_bar(
).encode(
    alt.X('Time:N'),
    alt.Y('value:Q')
)

alt.Chart(...)

In [8]:
alt.Chart(
    df.filter(pl.col('variable') == "běh").group_by(pl.col('Time').dt.month()).agg(pl.col('value').median()).sort(by='Time')
).mark_bar(
).encode(
    alt.X('Time:N'),
    alt.Y('value:Q')
)

alt.Chart(...)

In [25]:
df.select(pl.col('variable')).unique().to_series().to_list()

['VO2 max',
 'běhání',
 'běh',
 'cyklostezky',
 'silniční kola',
 'nosič na kolo',
 'duše kolo',
 'boty na běhání',
 'jak začít běhat',
 'gravel kolo',
 'elektrokola',
 'cyklobazar']

In [27]:
alt.Chart(
    df.filter(pl.col('variable').str.contains('boty na běhání')).group_by(pl.col('Time').dt.month()).agg(pl.col('value').mean()).sort(by='Time')
).mark_bar(
).encode(
    alt.X('Time:N'),
    alt.Y('value:Q')
)

alt.Chart(...)

In [29]:
alt.Chart(
    df.filter(pl.col('variable').str.contains('běh')).group_by(pl.col('Time').dt.month()).agg(pl.col('value').mean()).sort(by='Time')
).mark_bar(
).encode(
    alt.X('Time:N'),
    alt.Y('value:Q')
)

alt.Chart(...)

In [10]:
alt.Chart(
    df.filter(pl.col('variable').str.contains('kolo')).group_by(pl.col('Time').dt.month()).agg(pl.col('value').mean()).sort(by='Time')
).mark_bar(
).encode(
    alt.X('Time:N'),
    alt.Y('value:Q')
)

alt.Chart(...)

In [11]:
alt.Chart(
    df.filter(pl.col('variable').str.contains('běh')).group_by(pl.col('Time').dt.month()).agg(pl.col('value').mean()).sort(by='Time')
).mark_bar(
).encode(
    alt.X('Time:N'),
    alt.Y('value:Q')
)

alt.Chart(...)