In [43]:
import polars as pl

In [44]:
df1 = pl.read_json('data/korelace_behani.json').with_columns(pl.lit("běh").alias("sport")).rename({'korelace s počtem běhů':'korelace s počtem výkonů'})
df2 = pl.read_json('data/korelace_cyklistika.json').with_columns(pl.lit("cyklistika").alias("sport")).rename({'korelace s počtem jízd':'korelace s počtem výkonů'})
df_korelace = pl.concat([df1, df2])
df_korelace

shape: (16, 3)
┌─────────────────────────────────┬──────────────────────────┬────────────┐
│ index                           ┆ korelace s počtem výkonů ┆ sport      │
│ ---                             ┆ ---                      ┆ ---        │
│ str                             ┆ f64                      ┆ str        │
╞═════════════════════════════════╪══════════════════════════╪════════════╡
│ denní teplota 15 až 20 °C       ┆ 0.127737                 ┆ běh        │
│ nepracovní den                  ┆ 0.125371                 ┆ běh        │
│ mezitýdenní ochlazení o 4 až 6… ┆ 0.122009                 ┆ běh        │
│ denní teplota 20 až 25 °C       ┆ 0.093746                 ┆ běh        │
│ srážky nad 5 mm                 ┆ -0.122458                ┆ běh        │
│ …                               ┆ …                        ┆ …          │
│ letní prázdniny                 ┆ 0.439731                 ┆ cyklistika │
│ vlhkost vzduchu nad 89 %        ┆ -0.264851                ┆ cyklistika │
│ denní teplota 5 až 10 °C        ┆ -0.293005                ┆ cyklistika │
│ den bez slunce                  ┆ -0.438756                ┆ cyklistika │
│ denní teplota 0 až 5 °C         ┆ -0.469265                ┆ cyklistika │
└─────────────────────────────────┴──────────────────────────┴────────────┘

In [45]:
df_korelace.write_json("data/graf_korelace.json")

In [46]:
df1 = pl.read_json('data/graf_rok_behani.json').with_columns(pl.lit("běh").alias("sport"))
df2 = pl.read_json('data/graf_rok_cyklo.json').with_columns(pl.lit("cyklistika").alias("sport"))
df_pokusy = pl.concat([df1, df2])
df_pokusy

shape: (124, 4)
┌──────┬──────┬─────────────┬────────────┐
│ year ┆ week ┆ effort_diff ┆ sport      │
│ ---  ┆ ---  ┆ ---         ┆ ---        │
│ i64  ┆ i64  ┆ f64         ┆ str        │
╞══════╪══════╪═════════════╪════════════╡
│ 2025 ┆ 1    ┆ 1085.0      ┆ běh        │
│ 2025 ┆ 2    ┆ 1179.0      ┆ běh        │
│ 2025 ┆ 3    ┆ 1128.0      ┆ běh        │
│ 2025 ┆ 4    ┆ 1250.0      ┆ běh        │
│ 2025 ┆ 5    ┆ 1235.0      ┆ běh        │
│ …    ┆ …    ┆ …           ┆ …          │
│ 2026 ┆ 6    ┆ 597.0       ┆ cyklistika │
│ 2026 ┆ 7    ┆ 834.0       ┆ cyklistika │
│ 2026 ┆ 8    ┆ 732.0       ┆ cyklistika │
│ 2026 ┆ 9    ┆ 3078.0      ┆ cyklistika │
│ 2026 ┆ 10   ┆ 3845.0      ┆ cyklistika │
└──────┴──────┴─────────────┴────────────┘

In [47]:
df_pokusy.write_json("data/graf_pokusy.json")